#!/bin/bash
gcc ../battlemain.cpp Position.cpp Character.cpp Player.cpp Npc.cpp Interaction.cpp Skill.cpp Object.cpp Battle.cpp Map.cpp Capimon.cpp -lallegro -lallegro_image -lallegro_font -lallegro_ttf -lallegro_audio -lallegro_acodec
